import '../../shared/models/product.dart';

class ProductRepository {
  static final List<Product> allProducts = [
    // Laptops
    Product(
      id: '1',
      name: 'MacBook Pro M2',
      category: 'Laptops',
      description: 'The new MacBook Pro delivers game-changing performance for pros. With the powerful M2 Pro or the even more powerful M2 Max, you can tackle demanding projects and enjoy an all-day battery life.',
      price: 1999,
      originalPrice: 2199,
      discount: 10,
      image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAFADU2k9s9yi9OiJkrklAPB1BHzW2rjXuwOcoqnMSBgJ3wQZNZLX4gHrdfpapXKyxWZbAStYDdiAlwdl6v8YheC-klwGoTD9868M3mgpMOUmReXgVWMlS-uZyPzI0qLDhW-BRiIfKm7jFOY1bbEnW_SoP7xuX_D9d50W5z0GCTZGInY41hfUImHZbAnJbNvXswXR6iB8MFf22QpFD6YKbLyaQ4wo9nefxW2-JnUr6k2yD4H4n25dVZMYUwI5G0nxjkWLbkxM5nV6w',
      rating: 4.9,
      reviewsCount: 1240,
      specifications: ['Apple M2 Pro Chip', '16GB Unified Memory', '512GB SSD Storage', '14.2-inch Liquid Retina XDR display'],
    ),
    Product(
      id: 'l2',
      name: 'Dell XPS 15',
      category: 'Laptops',
      description: 'The XPS 15 is the perfect balance of power and portability. Immerse yourself in content with stunning panels and powerful performance.',
      price: 1849,
      originalPrice: 1849,
      discount: 0,
      image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCHv7Kxy_AE2JWPWgzImlSF2H2mff5uAz5guGPuR5mjWoWwsK3awEQ3J6zz9rvi8AP0ncSSobi1_b1STUURBq6Cx-dZZZirvCreVZDOqeKdm57WdXrgQ-lPrtF-1k-jd_JcFLD9yd3s8MnJca8r1F7Hpxl89KwXVG8jA2gALX2UzM9sLZNqXhn5YfHEFmgYLVokDhhprB3kpX1m9fV7vR7m86p576p4rtHZfDpoe6eDveekGUmfT-WZgIDl6zwCjUW4VGenZeZxJII',
      rating: 4.7,
      reviewsCount: 850,
      specifications: ['Intel Core i7-13700H', '16GB DDR5 RAM', '1TB M.2 PCIe NVMe SSD', '15.6" FHD+ display'],
    ),
    // Audio
    Product(
      id: '2',
      name: 'Sony WH-1000XM5',
      category: 'Audio',
      description: 'Industry-leading noise cancellation optimized to you. Magnificent Sound, engineered to perfection. Crystal clear hands-free calling.',
      price: 349,
      originalPrice: 399,
      discount: 12,
      image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAuOxkQWBkSY2790hLPOUf1TwudUCYMbK0xuyTg1Xqg8t7PpGJ9rhvj-6oHoPNXd5fE28yF2V5XnoBWAFhALQwlc-DsJejPZ4KpaBDa0PDXmjYO1JAsXbARbVgRE6eIbOfm8Zz-HSQFxwBCnDta-zMoGM09IT9fEn5QLaPkBKVCZBmEetdt0FHK4qiuuskSiGlYkPgDquQrNy-SX_vjqahEwp7naIbXF4-bYMFc9o7_qdfCJy2B9Kmrw-TdPxlXyq7ypS9LikqNeYM',
      rating: 4.8,
      reviewsCount: 2450,
      specifications: ['30-hour battery life', 'Touch sensor controls', 'Speak-to-chat technology'],
    ),
    // Gaming
    Product(
      id: '3',
      name: 'Razer Huntsman V2',
      category: 'Gaming',
      description: 'The world’s fastest optical gaming keyboard. With zero-latency and high-end features, victory is just a keystroke away.',
      price: 159,
      originalPrice: 199,
      discount: 20,
      image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC2b2iRelipNbABODEwcOUmm74niEzOY0ZuUgFXMLmfA6kidTEPbb0yE4bDHvbIUW_pXs5TrP4Tfiy26t4FlGlwkJ-G_lZkqMZLnAFaaeiylDrkOD9lpMlzTr5ozo0gkZTqcTONkomzb2s4Rv9_K_BMdJE0fkhKfnxYDcLErgiDvEodm8Loz7LLof1PMKJpqI8ak5Lhx9fljpHIYjZz0JPZRf2mwpLdXUtn4c4vFvEUfAN4H3VDBghNef-bA9-9uKFNA6YcNAXm9GY',
      rating: 4.7,
      reviewsCount: 920,
      specifications: ['Razer™ Linear Optical Switches', 'Doubleshot PBT Keycaps', 'Ergonomic Wrist Rest'],
    ),
    Product(
      id: 'g2',
      name: 'Logitech G Pro X Superlight',
      category: 'Gaming',
      description: 'The world’s lightest wireless gaming mouse. Designed with the world’s leading esports pros to deliver the fastest performance.',
      price: 129,
      originalPrice: 149,
      discount: 13,
      image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBlYO3SBeUD5X-_S81am-WnEOFKU9p37I__eTWNMB0lENCzxP5XbaGEAk_nFahQ8kE2FtWn0yIaRpyMa-oCSUoQ20iBZSqbh7JQM229xRCqpTmB7v-mPllL0KXIQ7qxhZJvGKx7ahVisFg8HgRcLt4eVjMa3O_hHT1GdFA910RtrOXcaz832qX_jZ4FpSXTCgUFdhJjviwNos3J73yKMOigvGn37Yg4gw99V5jPcisdP04EaNg73FKDiDrXxmqOFB_PUhlvoI8pQ7o',
      rating: 4.9,
      reviewsCount: 1800,
      specifications: ['<63g weight', 'HERO 25K Sensor', '70h Battery Life'],
    ),
    // Wearables
    Product(
      id: 'w1',
      name: 'Apple Watch Ultra',
      category: 'Wearables',
      description: 'The most rugged and capable Apple Watch ever. Designed for exploration, adventure, and endurance.',
      price: 799,
      originalPrice: 799,
      discount: 0,
      image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDGcA---SRf1kKdmK5yRUNcLeEmJXx0pIiY4bN01u3_2Mmc3Z-8qBTJFAHPe4g3BZTWCIPrJkta2gAOeQADqZXQnJErUD-mPWIe4kvk3FH9oniy21nUUqlF7CVQi7yNgW_P-zonGX7YgsbnHWN_hx4K5fGTWXud_HlKQ-etm_TW--2-43fZ0nvwgz6OEKbucY07EhwrdIB6lHBjCyWdVROv4vX9bcCTYnmuIW1rnN_FVfx5e1XuzxnKjXlTUE65olsTFLB6nOfNiDk',
      rating: 4.8,
      reviewsCount: 650,
      specifications: ['Titanium case', 'Up to 60h battery life', 'Precision dual-frequency GPS'],
    ),
    // Phones
    Product(
      id: 'p1',
      name: 'iPhone 15 Pro',
      category: 'Phones',
      description: 'The first iPhone to feature an aerospace‑grade titanium design, using the same alloy that spacecraft use for missions to Mars.',
      price: 999,
      originalPrice: 999,
      discount: 0,
      image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC2b2iRelipNbABODEwcOUmm74niEzOY0ZuUgFXMLmfA6kidTEPbb0yE4bDHvbIUW_pXs5TrP4Tfiy26t4FlGlwkJ-G_lZkqMZLnAFaaeiylDrkOD9lpMlzTr5ozo0gkZTqcTONkomzb2s4Rv9_K_BMdJE0fkhKfnxYDcLErgiDvEodm8Loz7LLof1PMKJpqI8ak5Lhx9fljpHIYjZz0JPZRf2mwpLdXUtn4c4vFvEUfAN4H3VDBghNef-bA9-9uKFNA6YcNAXm9GY',
      rating: 4.9,
      reviewsCount: 3200,
      specifications: ['A17 Pro chip', 'Pro camera system', 'USB-C Support'],
    ),
    Product(
      id: 'p2',
      name: 'Samsung Galaxy S23 Ultra',
      category: 'Phones',
      description: 'More innovation, less footprint. S23 Ultra’s striking symmetrical design returns with one major difference: recycled and eco-conscious materials.',
      price: 1199,
      originalPrice: 1199,
      discount: 0,
      image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAuOxkQWBkSY2790hLPOUf1TwudUCYMbK0xuyTg1Xqg8t7PpGJ9rhvj-6oHoPNXd5fE28yF2V5XnoBWAFhALQwlc-DsJejPZ4KpaBDa0PDXmjYO1JAsXbARbVgRE6eIbOfm8Zz-HSQFxwBCnDta-zMoGM09IT9fEn5QLaPkBKVCZBmEetdt0FHK4qiuuskSiGlYkPgDquQrNy-SX_vjqahEwp7naIbXF4-bYMFc9o7_qdfCJy2B9Kmrw-TdPxlXyq7ypS9LikqNeYM',
      rating: 4.8,
      reviewsCount: 2100,
      specifications: ['Snapdragon 8 Gen 2', '200MP Camera', 'Built-in S Pen'],
    ),
    // Smart Home
    Product(
      id: 'sh1',
      name: 'Philips Hue Starter Kit',
      category: 'Smart Home',
      description: 'The easiest way to get started with smart lighting. Control your lights with your voice or your phone.',
      price: 159,
      originalPrice: 199,
      discount: 20,
      image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDGcA---SRf1kKdmK5yRUNcLeEmJXx0pIiY4bN01u3_2Mmc3Z-8qBTJFAHPe4g3BZTWCIPrJkta2gAOeQADqZXQnJErUD-mPWIe4kvk3FH9oniy21nUUqlF7CVQi7yNgW_P-zonGX7YgsbnHWN_hx4K5fGTWXud_HlKQ-etm_TW--2-43fZ0nvwgz6OEKbucY07EhwrdIB6lHBjCyWdVROv4vX9bcCTYnmuIW1rnN_FVfx5e1XuzxnKjXlTUE65olsTFLB6nOfNiDk',
      rating: 4.5,
      reviewsCount: 1200,
      specifications: ['Bluetooth & Hue Bridge compatible', '16 million colors', 'Dimmable'],
    ),
    // Cameras
    Product(
      id: 'c1',
      name: 'Sony A7 IV',
      category: 'Cameras',
      description: 'The Sony A7 IV is a powerhouse hybrid camera with a 33MP sensor, incredible autofocus, and 4K 60p video.',
      price: 2499,
      originalPrice: 2499,
      discount: 0,
      image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAuOxkQWBkSY2790hLPOUf1TwudUCYMbK0xuyTg1Xqg8t7PpGJ9rhvj-6oHoPNXd5fE28yF2V5XnoBWAFhALQwlc-DsJejPZ4KpaBDa0PDXmjYO1JAsXbARbVgRE6eIbOfm8Zz-HSQFxwBCnDta-zMoGM09IT9fEn5QLaPkBKVCZBmEetdt0FHK4qiuuskSiGlYkPgDquQrNy-SX_vjqahEwp7naIbXF4-bYMFc9o7_qdfCJy2B9Kmrw-TdPxlXyq7ypS9LikqNeYM',
      rating: 4.9,
      reviewsCount: 450,
      specifications: ['33MP Full-Frame Sensor', '759 phase-detection AF points', '4K 60p 10-bit 4:2:2'],
    ),
    // Accessories
    Product(
      id: 'a1',
      name: 'Apple Magic Trackpad',
      category: 'Accessories',
      description: 'Wireless and rechargeable, Magic Trackpad includes the full range of Multi-Touch gestures and Force Touch technology.',
      price: 129,
      originalPrice: 129,
      discount: 0,
      image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBlYO3SBeUD5X-_S81am-WnEOFKU9p37I__eTWNMB0lENCzxP5XbaGEAk_nFahQ8kE2FtWn0yIaRpyMa-oCSUoQ20iBZSqbh7JQM229xRCqpTmB7v-mPllL0KXIQ7qxhZJvGKx7ahVisFg8HgRcLt4eVjMa3O_hHT1GdFA910RtrOXcaz832qX_jZ4FpSXTCgUFdhJjviwNos3J73yKMOigvGn37Yg4gw99V5jPcisdP04EaNg73FKDiDrXxmqOFB_PUhlvoI8pQ7o',
      rating: 4.7,
      reviewsCount: 1500,
      specifications: ['Multi-Touch surface', 'Force Touch technology', 'Rechargeable battery'],
    ),
  ];
}
